#!/bin/bash

export SBCL_HOME=/usr/local/lib/sbcl

# change to the directory of this script
cd $(cd `dirname $(test -L "$0" && readlink "$0" || echo "$0")` && pwd -P)

LC_CTYPE=en_US.UTF-8
export LC_CTYPE

if [ ! -f "/mnt/projects/cores/hackathon.core" ] ; then
/usr/local/bin/sbcl \
  --noinform \
  --dynamic-space-size 1024 \
  --eval "(progn (defparameter cl-user::*project* :hackathon) (load \"start.lisp\") (in-package :hackathon))" \
  "$@"
if [[ $? != 0 ]]; then
echo Error with core creation.
exit -1
fi
fi

/usr/local/bin/sbcl \
  --core "/mnt/projects/cores/hackathon.core" \
  --noinform \
  --dynamic-space-size 1024 \
  --eval "(progn (defparameter cl-user::*project* :hackathon) (load \"start.lisp\") (in-package :hackathon))" \
  "$@"
